[package]
name = "hyperlight-unikraft-mini"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4", features = ["derive"] }
hyperlight-common = { git = "https://github.com/danbugs/hyperlight.git", branch = "danbugs/fix-restore-rss-v0.16" }
hyperlight-host = { git = "https://github.com/danbugs/hyperlight.git", branch = "danbugs/fix-restore-rss-v0.16" }
